// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211085958_DropdownOption")]
    partial class DropdownOption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BaseComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrackerId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackerId");

                    b.ToTable("TrackerComponents");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.DropdownOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DropdownComponentId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DropdownComponentId");

                    b.ToTable("DropdownOptionComponents");
                });

            modelBuilder.Entity("backend.Models.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Trackers");
                });

            modelBuilder.Entity("backend.Models.DropdownComponent", b =>
                {
                    b.HasBaseType("backend.Models.BaseComponent");

                    b.ToTable("DropdownComponents");
                });

            modelBuilder.Entity("backend.Models.TextboxComponent", b =>
                {
                    b.HasBaseType("backend.Models.BaseComponent");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.ToTable("TextboxComponents");
                });

            modelBuilder.Entity("backend.Models.BaseComponent", b =>
                {
                    b.HasOne("backend.Models.Tracker", "Tracker")
                        .WithMany("Components")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("backend.Models.DropdownOption", b =>
                {
                    b.HasOne("backend.Models.DropdownComponent", "DropdownComponent")
                        .WithMany("Options")
                        .HasForeignKey("DropdownComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DropdownComponent");
                });

            modelBuilder.Entity("backend.Models.DropdownComponent", b =>
                {
                    b.HasOne("backend.Models.BaseComponent", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.DropdownComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.TextboxComponent", b =>
                {
                    b.HasOne("backend.Models.BaseComponent", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.TextboxComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Tracker", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("backend.Models.DropdownComponent", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
